-- JUYU Domain Check backend schema
-- Run once in Supabase SQL Editor, then set SUPABASE_URL and
-- SUPABASE_SERVICE_ROLE_KEY only in the Bot's server environment.

create table if not exists public.domain_reports (
  report_token text primary key,
  telegram_user_id bigint not null,
  source text not null default 'direct',
  domain text not null,
  intent text check (intent is null or intent in ('owner', 'buyer', 'research')),
  -- The following legacy score columns remain only for backward compatibility.
  -- JUYU-EVIDENCE-2.1 does not expose or calculate a proprietary domain score.
  score smallint check (score between 0 and 100),
  grade text check (grade in ('S', 'A', 'B', 'C', 'D')),
  score_version text,
  confidence text check (confidence in ('low', 'medium')),
  data_coverage smallint check (data_coverage between 0 and 100),
  dimension_scores jsonb,
  report jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.growth_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  telegram_user_id bigint not null,
  source text not null default 'direct',
  domain text,
  report_token text,
  intent text check (intent is null or intent in ('owner', 'buyer', 'research')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.user_profiles (
  telegram_user_id bigint primary key,
  telegram_username text,
  telegram_first_name text,
  telegram_last_name text,
  first_source text not null default 'direct',
  last_source text not null default 'direct',
  last_source_label text not null default '直接打开 Telegram Bot',
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create table if not exists public.bot_sessions (
  telegram_user_id bigint primary key references public.user_profiles(telegram_user_id) on delete cascade,
  flow text not null check (flow in ('buy', 'sell', 'register', 'contact')),
  step text not null,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.leads (
  id bigint generated always as identity primary key,
  lead_type text not null check (lead_type in ('buy', 'sell', 'contact')),
  telegram_user_id bigint not null references public.user_profiles(telegram_user_id) on delete cascade,
  username text not null default '',
  data jsonb not null default '{}'::jsonb,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

create index if not exists domain_reports_user_created_idx
  on public.domain_reports (telegram_user_id, created_at desc);
create index if not exists domain_reports_domain_created_idx
  on public.domain_reports (domain, created_at desc);
create index if not exists growth_events_name_created_idx
  on public.growth_events (event_name, created_at desc);
create index if not exists growth_events_source_created_idx
  on public.growth_events (source, created_at desc);
create index if not exists growth_events_user_created_idx
  on public.growth_events (telegram_user_id, created_at desc);
create index if not exists leads_created_at_idx
  on public.leads (created_at desc);
create index if not exists leads_type_status_idx
  on public.leads (lead_type, status, created_at desc);

-- Idempotent upgrade for projects created with the former required score columns.
alter table public.domain_reports alter column score drop not null;
alter table public.domain_reports alter column grade drop not null;
alter table public.domain_reports alter column score_version drop not null;
alter table public.domain_reports alter column confidence drop not null;
alter table public.domain_reports alter column data_coverage drop not null;
alter table public.domain_reports alter column dimension_scores drop not null;
alter table public.domain_reports alter column dimension_scores drop default;

-- Keep the original attribution code for analytics, and add a readable label
-- for people reviewing user_profiles in Supabase.
alter table public.user_profiles add column if not exists last_source_label text;
alter table public.user_profiles add column if not exists telegram_username text;
alter table public.user_profiles add column if not exists telegram_first_name text;
alter table public.user_profiles add column if not exists telegram_last_name text;

update public.user_profiles
set last_source_label = case
  when last_source = 'direct' then '直接打开 Telegram Bot'
  when last_source = 'channel' then 'JUYU Telegram 频道'
  when last_source = 'juyucom' then 'JUYU 官网'
  when last_source = 'share' then '报告分享入口'
  when last_source = 'referral' then '朋友分享链接'
  when last_source = 'juyu_check_bot' then 'JUYU 域名体检 Bot'
  when last_source = 'juyu_domain_bot' then 'JUYU 聚域助手'
  when last_source like 'morningbrief\_%' escape '\' then 'Telegram 频道活动：' || last_source
  else '活动来源：' || last_source
end
where last_source_label is null or last_source_label = '';

alter table public.user_profiles alter column last_source_label set default '直接打开 Telegram Bot';
alter table public.user_profiles alter column last_source_label set not null;

update public.domain_reports
set score = null,
    grade = null,
    score_version = null,
    confidence = null,
    data_coverage = null,
    dimension_scores = null
where coalesce(report->>'reportVersion', '') like 'JUYU-EVIDENCE-%';

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists domain_reports_set_updated_at on public.domain_reports;
create trigger domain_reports_set_updated_at
before update on public.domain_reports
for each row execute function public.set_updated_at();

create or replace function public.clear_legacy_domain_scores()
returns trigger
language plpgsql
as $$
begin
  if coalesce(new.report->>'reportVersion', '') like 'JUYU-EVIDENCE-%' then
    new.score = null;
    new.grade = null;
    new.score_version = null;
    new.confidence = null;
    new.data_coverage = null;
    new.dimension_scores = null;
  end if;
  return new;
end;
$$;

drop trigger if exists domain_reports_clear_legacy_scores on public.domain_reports;
create trigger domain_reports_clear_legacy_scores
before insert or update on public.domain_reports
for each row execute function public.clear_legacy_domain_scores();

alter table public.domain_reports enable row level security;
alter table public.growth_events enable row level security;
alter table public.user_profiles enable row level security;
alter table public.bot_sessions enable row level security;
alter table public.leads enable row level security;

revoke all on table public.bot_sessions from anon, authenticated;
revoke all on table public.leads from anon, authenticated;
grant all on table public.bot_sessions to service_role;
grant all on table public.leads to service_role;
grant usage, select on all sequences in schema public to service_role;

-- No public policies are intentionally created. The Bot backend uses the
-- Service Role Key, which bypasses RLS. Never expose that key to a Mini App.
